# Generated by Django 3.2.3 on 2021-05-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy',
        ),
    ]
