# Generated by Django 3.2.3 on 2021-06-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('source', '-modified'), 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
