# Generated by Django 2.1.5 on 2019-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddVacancyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('vacancy', models.TextField(max_length=600, verbose_name='Описание вакансии')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=125, verbose_name='Имя отправителя')),
                ('contacts', models.CharField(max_length=125, verbose_name='Контакты')),
                ('body', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
