# Generated by Django 2.1.5 on 2019-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvacancymessage',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='modified',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
