# Generated by Django 2.1.5 on 2019-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_addvacancymessage_save_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addvacancymessage',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='addvacancymessage',
            name='contacts',
            field=models.CharField(default='', max_length=125, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addvacancymessage',
            name='description',
            field=models.TextField(default='', verbose_name='Описание вакансии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addvacancymessage',
            name='employer',
            field=models.CharField(default='', max_length=255, verbose_name='Название организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addvacancymessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название вакансии'),
        ),
    ]
