# Generated by Django 2.1.5 on 2019-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20190605_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addvacancymessage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'ordering': ('-created',)},
        ),
    ]
