# Generated by Django 3.2.3 on 2021-06-01 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20210527_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addvacancymessage',
            options={'ordering': ('-created',), 'verbose_name': 'Сообщение о вакансии', 'verbose_name_plural': 'Сообщения о вакансиях'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'ordering': ('-created',), 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.RemoveField(
            model_name='addvacancymessage',
            name='save_vacancy',
        ),
    ]
